spring:
  rabbitmq:
    host: 119.45.191.248
    port: 5672
    username: mingrui
    password: 123456
  cloud:
    # 启用bus
    bus:
      enabled: true
      # 启用消息跟踪
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
