server:
  port: 8888
spring:
  security:
    user:
      # 配置中心用户
      name: mingrui
      # 配置中心密码
      password: 123456
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/shen-yaqi/mingrui.git
          search-paths: spring-cloud-parent/config-server/src/main/resources/config
          username: shenyaqiii@163.com
          password: shenyaqi.110
      label: master