server:
  port: 8888
spring:
  security:
    user:
      # 配置中心用户
      name: mingrui
      # 配置中心密码
      password: 123456
  application:
    name: config-server
  profiles:
    # 使用本地配置文件
    active: native
  cloud:
    config:
      server:
        native:
          # 声明本地配置文件目录
          search-locations: file:/shenyaqi/spring-cloud/conf
eureka:
  client:
    service-url:
      # 指定注册中心的服务地址
      defaultZone: http://119.45.191.248:8761/eureka/
  # 启用外网ip,部署到外网服务器需要加此项配置
  instance:
    prefer-ip-address: true
    ip-address: 119.45.191.248
    non-secure-port: 8888