server:
  port: 8888
spring:
  security:
    user:
      name: mingrui
      password: 123456
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
