server:
  port: 8888
spring:
  security:
    user:
      # 配置中心用户
      name: mingrui
      # 配置中心密码
      password: 123456
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://github.com/shen-yaqi/mingrui.git
          # 配置文件所在目录
          search-paths: spring-cloud-parent/config-server/src/main/resources/config
          # git账号
          username: shenyaqiii@163.com
          # git密码
          password: shenyaqi.110
      #分支
      label: master

eureka:
  client:
    service-url:
      # 指定注册中心的服务地址
      defaultZone: http://119.45.191.248:8761/eureka/